"use strict";

export const siteName = document.getElementById("siteName");
export const siteUrl = document.getElementById("siteUrl");
export const btnSubmit = document.getElementById("btnSubmit");
export const updateModal = document.getElementById("updateModal");
export const deleteModal = document.getElementById("deleteModal");
export const bookmarksContainer = document.getElementById("bookmarksData");
export const btnConfirmDelete = document.getElementById("btnConfirmDelete");
export const updateName = document.getElementById("updateName");
export const updateUrl = document.getElementById("updateUrl");
export const btnConfirmUpdate = document.getElementById("btnConfirmUpdate");
export const btnCloseUpdate = document.getElementById("btnCloseUpdate");
export const btnCloseDelete = document.getElementById("btnCloseDelete");
export const btnCancelDelete = document.getElementById("btnCancel");
export const searchInput = document.getElementById("searchInput");
export const nameError = document.getElementById("nameError");
export const urlError = document.getElementById("urlError");
export const updateNameError = document.getElementById("updateNameError");
export const updateUrlError = document.getElementById("updateUrlError");
export const successModal = document.getElementById("successModal");
